# App Config: LXP
APP_NAME="lxp"
APP_BRANCH="feature/lxp"
APP_JAR_PATH="lxp-2.3.6.jar"
APP_LICENSE="AAABrA0ODAoPeNp1kt2O0zAQhe/9FCNxV8lpUkDQSpGgidldsZtUTbLAAheuO20NqW3ZTpe+Pd6k1fKjSvbVzBx/54xfVNxDjgImU4iT2cvJLJnC1V0Nkzh5S4puv0JbbhqH1qU0IZlWngtf8D2ma8Otlm73jvuWOye5ioTeE9N2W6lcNIpCozxg6m2HZNFZseMOc+4xDdpTGifhkFspUDmsjwZ70Zzds9tyw5bnCvtlpD32Y4s3k/j6jMDuuGwvMVRoD2hv8nR+Na3p5+b+Ff348HBN53HyiVTdygkrjZdaDXCj0agoa/qhXNLFssybrL4pC9pULBTSzGJ4fA2rI/gdwgkLmBJ6jRaM1T9QePi68958m43HWx39BTNuhwmKw8T3CHINSntYS+etXHUeg7J04DWIznm9D2FHJPhTHhVX4v8MAle2ZO9rltP5lyfICzmcYEMQjfqp9KMiFSvScOnrOCal3XIlHe+DyPGArTbBUY3On22S3n2o/7u35y2HCs8woNohzByf0+2lTv5hoy08NcPQDdwYWJ9fdX8oXv4T7MDbbuDd8Dbg/QYPee+DMCwCFEyQh7Q4DuefuZq5ZchnhQZ4icj3AhRpb0dz2Rfjj/DULKEa0gCpLDMFFg==X02kk"
STANDALONE_EXTENSION=0
CUSTOM_JQL="project = TEST ORDER BY created DESC"
